INSERT INTO Article (id, title, content, date_published, auteur_id, categorie_id) VALUES
(1, 'Les Bienfaits de la Lavande pour la Relaxation', 
    'La lavande est reconnue pour ses propriétés relaxantes et apaisantes. Utilisée en aromathérapie, elle aide à réduire le stress et l’anxiété, favorisant ainsi un sommeil réparateur. Son huile essentielle est souvent diffusée dans les chambres à coucher ou ajoutée aux bains pour améliorer la qualité du sommeil. Les études montrent que la lavande peut également soulager les maux de tête et les douleurs musculaires.', 
    UNIX_TIMESTAMP(), 
    12, 
    1),
(2, 'Comment Utiliser l’Eucalyptus pour Améliorer la Respiration', 
    'L’huile essentielle d’eucalyptus est un remède naturel efficace contre les problèmes respiratoires. En inhalation, elle aide à dégager les voies respiratoires et à soulager les symptômes du rhume et de la sinusite. Vous pouvez également ajouter quelques gouttes d’eucalyptus à un bain chaud pour bénéficier de ses effets décongestionnants.', 
    UNIX_TIMESTAMP(), 
    20, 
    2),
(3, 'Les Secrets d’un Bain Relaxant avec les Huiles Essentielles', 
    'Un bain chaud enrichi d’huiles essentielles peut transformer votre routine de relaxation. Les huiles de lavande, de camomille et d’ylang-ylang sont particulièrement efficaces pour calmer l’esprit et détendre le corps. Mélangez quelques gouttes d’huiles essentielles avec une base d’huile végétale ou de lait en poudre avant d’ajouter à l’eau du bain pour une expérience apaisante.', 
    UNIX_TIMESTAMP(), 
    17, 
    3),
(4, 'Préparer un Spray Purifiant pour la Maison', 
    'Créer un spray purifiant maison est simple et efficace pour maintenir un environnement sain. Mélangez de l’eau distillée avec des huiles essentielles comme le citron et le tea tree. Ce spray non seulement désinfecte les surfaces, mais contribue également à purifier l’air de votre maison.', 
    UNIX_TIMESTAMP(), 
    22, 
    4),
(5, 'La Meilleure Huile Essentielle pour les Maux de Tête', 
    'L’huile essentielle de menthe poivrée est un excellent remède pour soulager les maux de tête. Ses propriétés rafraîchissantes et analgésiques peuvent aider à réduire la douleur lorsqu’elle est appliquée sur les tempes. Mélangez-la avec de l’huile de jojoba pour une application sûre et efficace.', 
    UNIX_TIMESTAMP(), 
    25, 
    5),
(6, 'Recette d’un Baume Anti-Stress à Base de Lavande', 
    'Préparez un baume anti-stress en mélangeant de l’huile essentielle de lavande avec de l’huile de coco et de la cire d’abeille. Ce baume peut être appliqué sur les poignets et les tempes pour aider à calmer l’anxiété et promouvoir la relaxation.', 
    UNIX_TIMESTAMP(), 
    30, 
    6),
(7, 'Utiliser les Huiles Essentielles pour un Sommeil Réparateur', 
    'Les huiles essentielles comme la lavande, la marjolaine et la camomille sont parfaites pour favoriser un sommeil réparateur. Diffusez ces huiles dans votre chambre avant de dormir ou ajoutez-les à votre bain du soir pour une meilleure qualité de sommeil.', 
    UNIX_TIMESTAMP(), 
    12, 
    7),
(8, 'La Puissance de la Camomille dans les Soins de Peau', 
    'L’huile essentielle de camomille est connue pour ses propriétés apaisantes et anti-inflammatoires. Elle est idéale pour les peaux sensibles et peut aider à réduire les rougeurs et les irritations. Intégrez-la dans vos soins quotidiens pour des résultats visibles.', 
    UNIX_TIMESTAMP(), 
    15, 
    8),
(9, 'Créer Votre Propre Sérum Capillaire Anti-Chute', 
    'Un sérum capillaire anti-chute peut être fabriqué en mélangeant de l’huile essentielle de romarin avec de l’huile de ricin et de l’huile de jojoba. Ce mélange nourrit le cuir chevelu et stimule la croissance des cheveux. Appliquez-le régulièrement pour des résultats optimaux.', 
    UNIX_TIMESTAMP(), 
    20, 
    9),
(10, 'Comment Fabriquer un Déodorant Naturel Efficace', 
    'Un déodorant maison peut être fabriqué en combinant de l’huile essentielle de lavande, du bicarbonate de soude et de l’huile de coco. Ce mélange est non seulement naturel, mais il aide également à lutter contre les mauvaises odeurs tout en respectant la peau.', 
    UNIX_TIMESTAMP(), 
    22, 
    10),
(11, 'L’Utilisation des Huiles Essentielles pour un Gommage Corporel Maison', 
    'Un gommage corporel fait maison peut être préparé en mélangeant du marc de café avec de l’huile essentielle d’orange et de l’huile de coco. Ce gommage aide à exfolier la peau, à améliorer la circulation et à la rendre plus douce.', 
    UNIX_TIMESTAMP(), 
    17, 
    11),
(12, 'Les Avantages des Sels de Bain Détox', 
    'Les sels de bain au citron sont parfaits pour un bain détoxifiant. Mélangez du sel d’Epsom avec de l’huile essentielle de citron et du bicarbonate de soude. Ajoutez ce mélange à votre bain pour aider à éliminer les toxines et relaxer vos muscles.', 
    UNIX_TIMESTAMP(), 
    25, 
    12),
(13, 'Préparer un Masque Purifiant pour le Visage', 
    'Un masque purifiant peut être préparé en combinant de l’argile verte avec de l’eau de rose et de l’huile essentielle de tea tree. Ce masque aide à nettoyer les pores, à réduire les imperfections et à purifier la peau.', 
    UNIX_TIMESTAMP(), 
    30, 
    13),
(14, 'Le Meilleur Sérum pour les Cils et Sourcils', 
    'Pour renforcer les cils et sourcils, préparez un sérum en mélangeant de l’huile de ricin avec de l’huile essentielle de romarin et de l’huile de vitamine E. Appliquez ce sérum régulièrement pour des cils et sourcils plus épais et plus forts.', 
    UNIX_TIMESTAMP(), 
    15, 
    14),
(15, 'Les Avantages de l’Huile d’Argan dans les Soins Capillaires', 
    'L’huile d’argan est riche en nutriments et idéale pour nourrir les cheveux secs et abîmés. Mélangez-la avec de l’huile essentielle d’ylang-ylang pour créer un traitement capillaire revitalisant. Appliquez le mélange sur les cheveux et laissez agir avant de rincer.', 
    UNIX_TIMESTAMP(), 
    17, 
    15),
(16, 'Créer une Brume d’Oreiller Relaxante pour la Nuit', 
    'Préparez une brume d’oreiller en mélangeant de l’eau distillée avec de l’huile essentielle de lavande et de l’alcool à friction. Vaporisez légèrement sur votre oreiller avant de dormir pour favoriser un sommeil paisible.', 
    UNIX_TIMESTAMP(), 
    20, 
    16),
(17, 'Les Bienfaits de l’Huile de Coco dans les Soins de la Peau', 
    'L’huile de coco est un hydratant naturel excellent pour la peau. Mélangez-la avec de l’huile essentielle de lavande pour créer une crème nourrissante. Appliquez sur la peau pour une hydratation en profondeur.', 
    UNIX_TIMESTAMP(), 
    25, 
    17),
(18, 'Comment Fabriquer une Lotion Hydratante pour Mains', 
    'Pour une lotion hydratante maison, mélangez du beurre de karité, de l’huile de coco et de l’huile essentielle de lavande. Ce mélange nourrit intensément les mains sèches et les rend douces et souples.', 
    UNIX_TIMESTAMP(), 
    30, 
    18),
(19, 'La Magie des Huiles Essentielles pour la Beauté du Visage', 
    'Les huiles essentielles comme la rose et la camomille sont excellentes pour la peau du visage. Créez un sérum en combinant ces huiles avec une base d’huile d’argan pour améliorer l’éclat de la peau et réduire les signes de vieillissement.', 
    UNIX_TIMESTAMP(), 
    12, 
    19),
(20, 'Préparer un Baume Chauffant pour les Douleurs Musculaires', 
    'Pour soulager les douleurs musculaires, mélangez de l’huile essentielle de gingembre avec de l’huile essentielle de poivre noir et de la cire d’abeille. Ce baume réchauffe et soulage les muscles endoloris.', 
    UNIX_TIMESTAMP(), 
    17, 
    20),
(21, 'Les Propriétés Anti-Moustiques de la Citronnelle', 
    'L’huile essentielle de citronnelle est un excellent répulsif naturel contre les moustiques. Vous pouvez créer un spray anti-moustiques en mélangeant de l’huile essentielle de citronnelle avec de l’eau et un peu d’alcool. Ce spray est efficace pour éloigner les insectes lors de vos soirées d’été en extérieur.', 
    UNIX_TIMESTAMP(), 
    22, 
    1),
(22, 'Comment Utiliser l’Huile d’Olive dans les Soins du Visage', 
    'L’huile d’olive est riche en antioxydants et en vitamines. Elle peut être utilisée pour démaquiller en douceur et hydrater la peau. Ajoutez quelques gouttes d’huile essentielle de rose pour un effet anti-âge et un parfum agréable.', 
    UNIX_TIMESTAMP(), 
    30, 
    2),
(23, 'Les Vertus de l’Huile Essentielle de Thym pour le Système Immunitaire', 
    'L’huile essentielle de thym est connue pour ses propriétés antibactériennes et antivirales. En diffusion ou en inhalation, elle aide à renforcer le système immunitaire et à prévenir les infections. Vous pouvez également l’ajouter à un bain chaud pour une action supplémentaire.', 
    UNIX_TIMESTAMP(), 
    12, 
    3),
(24, 'Préparer un Gommage Corporel au Sucre et à la Vanille', 
    'Un gommage corporel maison à base de sucre, d’huile de coco et d’huile essentielle de vanille est parfait pour exfolier et adoucir la peau. Le sucre élimine les cellules mortes tandis que l’huile de coco hydrate et l’huile essentielle de vanille apporte une touche parfumée.', 
    UNIX_TIMESTAMP(), 
    15, 
    4),
(25, 'Créer un Nettoyant Visage Naturel avec de l’Huile d’Arbre à Thé', 
    'Pour un nettoyant visage naturel, mélangez de l’huile d’arbre à thé avec du gel d’aloe vera et de l’huile de jojoba. Ce nettoyant aide à purifier la peau et à combattre les imperfections sans assécher.', 
    UNIX_TIMESTAMP(), 
    17, 
    5),
(26, 'Les Avantages de l’Huile Essentielle de Patchouli pour les Soins de la Peau', 
    'L’huile essentielle de patchouli possède des propriétés régénérantes et cicatrisantes. Elle est idéale pour les peaux matures ou abîmées. Mélangez-la avec une huile de base comme l’huile de rose musquée pour améliorer l’élasticité de la peau.', 
    UNIX_TIMESTAMP(), 
    20, 
    6),
(27, 'Comment Préparer un Tonique Rafraîchissant au Concombre et à la Menthe', 
    'Un tonique rafraîchissant peut être fabriqué en combinant du jus de concombre avec de l’hydrolat de menthe poivrée. Ce tonique aide à hydrater et à revitaliser la peau tout en lui donnant un effet rafraîchissant.', 
    UNIX_TIMESTAMP(), 
    22, 
    7),
(28, 'Les Propriétés Apaisantes de l’Huile Essentielle de Ylang-Ylang', 
    'L’huile essentielle d’ylang-ylang est connue pour ses propriétés relaxantes et équilibrantes. Elle est idéale pour soulager le stress et l’anxiété. Vous pouvez l’ajouter à votre diffuseur ou l’incorporer dans un massage pour un effet apaisant.', 
    UNIX_TIMESTAMP(), 
    25, 
    8),
(29, 'Créer une Lotion Apaisante pour Peaux Sensibles', 
    'Une lotion apaisante pour peaux sensibles peut être préparée en combinant de l’eau de rose, du gel d’aloe vera et de l’huile essentielle de camomille. Ce mélange calme les irritations et hydrate la peau délicate.', 
    UNIX_TIMESTAMP(), 
    30, 
    9),
(30, 'Utiliser l’Huile de Jojoba pour Équilibrer la Production de Sébum', 
    'L’huile de jojoba est idéale pour réguler la production de sébum et maintenir une peau équilibrée. Appliquez quelques gouttes sur votre visage après le nettoyage pour une hydratation légère qui ne bouche pas les pores.', 
    UNIX_TIMESTAMP(), 
    12, 
    10),
(31, 'L’Huile Essentielle de Citron pour Éclaircir l’Humeur', 
    'L’huile essentielle de citron est connue pour ses propriétés vivifiantes et énergisantes. Elle peut aider à améliorer l’humeur et à stimuler l’énergie mentale. Diffusez quelques gouttes de citron dans votre espace de travail pour une ambiance plus dynamique.', 
    UNIX_TIMESTAMP(), 
    17, 
    1),
(32, 'Comment Utiliser les Huiles Essentielles pour Soulager les Crampes', 
    'Les huiles essentielles de lavande et de camomille sont efficaces pour soulager les crampes musculaires. Mélangez ces huiles avec une huile de support comme l’huile d’amande douce et massez la zone affectée pour un soulagement rapide.', 
    UNIX_TIMESTAMP(), 
    20, 
    2),
(33, 'Préparer un Gommage pour les Pieds avec de l’Huile de Menthe', 
    'Un gommage pour les pieds peut être préparé en combinant du sel de mer, de l’huile de menthe poivrée et de l’huile de coco. Ce mélange exfolie les pieds en douceur tout en apportant une sensation de fraîcheur.', 
    UNIX_TIMESTAMP(), 
    22, 
    3),
(34, 'Les Bienfaits de l’Huile Essentielle d’Orange Douce pour la Peau', 
    'L’huile essentielle d’orange douce est idéale pour revitaliser la peau fatiguée. Ajoutez quelques gouttes à votre crème hydratante ou à un masque pour le visage pour un effet tonifiant et rafraîchissant.', 
    UNIX_TIMESTAMP(), 
    25, 
    4),
(35, 'Créer un Spray Énergisant pour la Maison avec du Citron et du Gingembre', 
    'Préparez un spray énergisant pour la maison en mélangeant de l’eau distillée avec des huiles essentielles de citron et de gingembre. Ce spray non seulement parfume agréablement l’air mais aide également à dynamiser votre espace.', 
    UNIX_TIMESTAMP(), 
    30, 
    5),
(36, 'Comment Utiliser l’Huile de Ricin pour Renforcer les Cheveux', 
    'L’huile de ricin est connue pour ses propriétés fortifiantes pour les cheveux. Appliquez-la directement sur le cuir chevelu ou ajoutez-la à vos masques capillaires pour encourager une croissance saine et renforcer les cheveux.', 
    UNIX_TIMESTAMP(), 
    12, 
    6),
(37, 'Les Vertus de l’Huile Essentielle de Géranium pour les Peaux Mixtes', 
    'L’huile essentielle de géranium est bénéfique pour les peaux mixtes en équilibrant la production de sébum. Mélangez-la avec une huile de base comme l’huile de jojoba et appliquez sur le visage pour un teint uniforme.', 
    UNIX_TIMESTAMP(), 
    15, 
    7),
(38, 'Préparer un Baume à Lèvres Naturel au Menthe et au Beurre de Karité', 
    'Un baume à lèvres naturel peut être préparé avec du beurre de karité, de l’huile de coco et de l’huile essentielle de menthe. Ce baume hydrate et protège les lèvres tout en leur donnant un goût rafraîchissant.', 
    UNIX_TIMESTAMP(), 
    20, 
    8),
(39, 'L’Huile Essentielle de Romarin pour Stimuler la Croissance des Cheveux', 
    'L’huile essentielle de romarin est connue pour stimuler la circulation sanguine dans le cuir chevelu, favorisant ainsi la croissance des cheveux. Ajoutez quelques gouttes à votre shampooing ou utilisez-la en massage sur le cuir chevelu.', 
    UNIX_TIMESTAMP(), 
    22, 
    9),
(40, 'Créer une Crème Anti-Âge Maison avec de l’Huile de Rose Musquée', 
    'Une crème anti-âge maison peut être fabriquée en combinant de l’huile de rose musquée avec de l’huile essentielle de lavande. Ce mélange hydrate en profondeur et aide à réduire les signes visibles du vieillissement.', 
    UNIX_TIMESTAMP(), 
    25, 
    10),
(41, 'Les Propriétés Purifiantes de l’Huile Essentielle de Lavande', 
    'L’huile essentielle de lavande possède des propriétés purifiantes qui peuvent aider à assainir l’air et à promouvoir un environnement plus sain. Utilisez-la dans un diffuseur pour bénéficier de ses effets purifiants et apaisants.', 
    UNIX_TIMESTAMP(), 
    30, 
    1),
(42, 'Comment Préparer un Masque Capillaire Nourrissant à l’Huile d’Argan', 
    'Préparez un masque capillaire nourrissant en combinant de l’huile d’argan avec de l’huile essentielle d’ylang-ylang. Appliquez ce masque sur les cheveux secs et abîmés pour les revitaliser et les rendre plus doux.', 
    UNIX_TIMESTAMP(), 
    12, 
    2),
(43, 'Les Bienfaits de l’Huile Essentielle de Camomille pour les Enfants', 
    'L’huile essentielle de camomille est douce et sûre pour les enfants. Elle est idéale pour calmer les enfants agités ou aider à traiter les irritations cutanées légères. Diluez-la toujours avec une huile de support avant utilisation.', 
    UNIX_TIMESTAMP(), 
    17, 
    3),
(44, 'Créer un Nettoyant Maison pour le Visage avec du Citron et du Miel', 
    'Un nettoyant maison efficace peut être préparé en mélangeant du jus de citron avec du miel et un peu d’eau. Ce nettoyant aide à éclaircir le teint et à éliminer les impuretés tout en hydratant la peau.', 
    UNIX_TIMESTAMP(), 
    20, 
    4),
(45, 'Les Propriétés Calmantes de l’Huile Essentielle de Bois de Santal', 
    'L’huile essentielle de bois de santal est réputée pour ses propriétés calmantes et relaxantes. Utilisez-la en diffusion ou en massage pour apaiser l’esprit et favoriser la méditation.', 
    UNIX_TIMESTAMP(), 
    22, 
    5),
(46, 'Comment Préparer un Masque Détoxifiant pour le Visage', 
    'Un masque détoxifiant peut être fabriqué en combinant de l’argile bentonite avec de l’eau et quelques gouttes d’huile essentielle de tea tree. Ce masque aide à éliminer les toxines et à purifier les pores.', 
    UNIX_TIMESTAMP(), 
    25, 
    6),
(47, 'Les Avantages de l’Huile Essentielle de Marjolaine pour le Sommeil', 
    'L’huile essentielle de marjolaine est bénéfique pour améliorer la qualité du sommeil. Diffusez-la dans votre chambre avant de dormir ou ajoutez-la à votre bain pour une relaxation profonde.', 
    UNIX_TIMESTAMP(), 
    30, 
    7),
(48, 'Créer un Baume Réparateur pour les Coudes et les Genoux', 
    'Préparez un baume réparateur en combinant de l’huile de coco, de la cire d’abeille et de l’huile essentielle de lavande. Ce baume est idéal pour nourrir et réparer les zones sèches et rugueuses comme les coudes et les genoux.', 
    UNIX_TIMESTAMP(), 
    12, 
    8),
(49, 'Les Propriétés Antiseptiques de l’Huile Essentielle de Clou de Girofle', 
    'L’huile essentielle de clou de girofle possède des propriétés antiseptiques puissantes. Utilisez-la en dilution pour traiter les coupures et les éraflures ou en diffusion pour purifier l’air.', 
    UNIX_TIMESTAMP(), 
    15, 
    9),
(50, 'Préparer un Sérum Hydratant pour les Cheveux Secs', 
    'Un sérum hydratant pour cheveux secs peut être fabriqué en combinant de l’huile de jojoba avec de l’huile essentielle de ylang-ylang. Appliquez ce sérum sur les longueurs et les pointes pour apporter une hydratation intense.', 
    UNIX_TIMESTAMP(), 
    20, 
    10),
(51, 'Les Bienfaits de l’Huile Essentielle de Cèdre pour la Peau', 
    'L’huile essentielle de cèdre est excellente pour les peaux grasses et sujettes aux imperfections. Ajoutez quelques gouttes à votre crème de nuit ou à votre sérum pour aider à réguler la production de sébum.', 
    UNIX_TIMESTAMP(), 
    22, 
    1),
(52, 'Comment Créer une Crème Nourrissante pour les Mains', 
    'Préparez une crème nourrissante pour les mains en combinant du beurre de karité, de l’huile de coco et quelques gouttes d’huile essentielle de lavande. Cette crème hydrate intensément et protège les mains des agressions extérieures.', 
    UNIX_TIMESTAMP(), 
    25, 
    2),
(53, 'Les Vertus Relaxantes de l’Huile Essentielle de Valériane', 
    'L’huile essentielle de valériane est idéale pour favoriser la relaxation et améliorer le sommeil. Utilisez-la en diffusion ou ajoutez quelques gouttes à votre bain du soir pour apaiser l’esprit et induire un sommeil réparateur.', 
    UNIX_TIMESTAMP(), 
    30, 
    3),
(54, 'Préparer un Gommage Doux pour le Visage avec de l’Huile d’Avocat', 
    'Un gommage doux pour le visage peut être préparé avec de l’huile d’avocat, du sucre fin et de l’huile essentielle de rose. Ce gommage exfolie en douceur tout en nourrissant et en hydratant la peau.', 
    UNIX_TIMESTAMP(), 
    12, 
    4),
(55, 'Les Avantages de l’Huile Essentielle de Patchouli pour les Cheveux', 
    'L’huile essentielle de patchouli peut aider à traiter les cheveux secs et abîmés. Ajoutez quelques gouttes à votre après-shampooing ou à un masque capillaire pour améliorer la texture et la brillance des cheveux.', 
    UNIX_TIMESTAMP(), 
    17, 
    5),
(56, 'Créer un Spray Déodorant Maison avec du Tea Tree', 
    'Préparez un déodorant naturel en mélangeant de l’eau distillée avec des huiles essentielles de tea tree et de citron. Ce spray offre une protection efficace contre les mauvaises odeurs tout en étant doux pour la peau.', 
    UNIX_TIMESTAMP(), 
    20, 
    6),
(57, 'Les Propriétés Hydratantes de l’Huile d’Argan pour le Visage', 
    'L’huile d’argan est riche en acides gras et en vitamine E, ce qui en fait un excellent hydratant pour le visage. Utilisez-la seule ou en combinaison avec de l’huile essentielle de géranium pour une peau éclatante et bien hydratée.', 
    UNIX_TIMESTAMP(), 
    22, 
    7),
(58, 'Préparer un Sérum de Nuit Nourrissant avec des Huiles Essentielles', 
    'Un sérum de nuit nourrissant peut être préparé en combinant de l’huile de rose musquée avec de l’huile essentielle de lavande. Appliquez ce sérum avant de dormir pour une peau réparée et revitalisée au réveil.', 
    UNIX_TIMESTAMP(), 
    25, 
    8),
(59, 'Comment Utiliser l’Huile Essentielle de Menthe Poivrée pour les Maux d’Estomac', 
    'L’huile essentielle de menthe poivrée est efficace pour soulager les maux d’estomac. Diluez-la avec une huile de support et massez doucement l’abdomen pour apaiser les crampes et les douleurs digestives.', 
    UNIX_TIMESTAMP(), 
    30, 
    9),
(60, 'Les Bienfaits de l’Huile Essentielle d’Ylang-Ylang pour le Stress', 
    'L’huile essentielle d’ylang-ylang est reconnue pour ses propriétés anti-stress. En diffusion ou en application locale, elle aide à réduire les niveaux de stress et à favoriser un état de calme.', 
    UNIX_TIMESTAMP(), 
    12, 
    10),
(61, 'Créer une Lotion Anti-Acné avec du Tea Tree et de l’Argile Verte', 
    'Préparez une lotion anti-acné en combinant de l’argile verte avec de l’eau et de l’huile essentielle de tea tree. Appliquez ce mélange sur les zones affectées pour aider à réduire les imperfections et purifier la peau.', 
    UNIX_TIMESTAMP(), 
    15, 
    1),
(62, 'Comment Utiliser l’Huile Essentielle de Citron pour Éclaircir les Taches de Pigmentation', 
    'L’huile essentielle de citron peut aider à éclaircir les taches de pigmentation lorsqu’elle est utilisée régulièrement. Mélangez-la avec une huile de support et appliquez-la sur les zones affectées avant de vous exposer au soleil.', 
    UNIX_TIMESTAMP(), 
    17, 
    2),
(63, 'Les Propriétés Revitalisantes de l’Huile Essentielle de Pamplemousse', 
    'L’huile essentielle de pamplemousse est revitalisante et énergisante. Utilisez-la en diffusion ou ajoutez-la à vos produits de soins pour stimuler votre humeur et dynamiser votre espace.', 
    UNIX_TIMESTAMP(), 
    20, 
    3),
(64, 'Préparer une Crème pour les Pieds à Base de Beurre de Karité et d’Huile de Menthe', 
    'Une crème nourrissante pour les pieds peut être préparée en combinant du beurre de karité, de l’huile de coco et quelques gouttes d’huile essentielle de menthe poivrée. Cette crème hydrate et rafraîchit les pieds secs et fatigués.', 
    UNIX_TIMESTAMP(), 
    22, 
    4),
(65, 'Les Bienfaits de l’Huile Essentielle de Bois de Hô pour la Peau Mature', 
    'L’huile essentielle de bois de hô est excellente pour les peaux matures en raison de ses propriétés régénérantes. Mélangez-la avec de l’huile de rose musquée pour un sérum anti-âge qui nourrit et raffermit la peau.', 
    UNIX_TIMESTAMP(), 
    25, 
    5),
(66, 'Comment Créer un Baume Apaisant pour les Brûlures Legères', 
    'Un baume apaisant pour les brûlures légères peut être fabriqué en combinant de l’huile de coco, de la cire d’abeille et de l’huile essentielle de lavande. Ce baume aide à calmer la peau et à favoriser la guérison.', 
    UNIX_TIMESTAMP(), 
    30, 
    6),
(67, 'Les Propriétés Purifiantes de l’Huile Essentielle de Lavande pour les Cheveux Gras', 
    'L’huile essentielle de lavande peut aider à équilibrer la production de sébum des cheveux gras. Ajoutez quelques gouttes à votre shampooing ou à un masque capillaire pour des cheveux plus frais et plus propres.', 
    UNIX_TIMESTAMP(), 
    12, 
    7),
(68, 'Préparer une Huile de Massage Apaisante avec de l’Huile de Jojoba et de Camomille', 
    'Préparez une huile de massage apaisante en mélangeant de l’huile de jojoba avec de l’huile essentielle de camomille. Ce mélange est idéal pour un massage relaxant qui aide à soulager les tensions et les douleurs musculaires.', 
    UNIX_TIMESTAMP(), 
    17, 
    8),
(69, 'Les Vertus Détoxifiantes de l’Huile Essentielle de Géranium', 
    'L’huile essentielle de géranium aide à détoxifier le corps en stimulant la circulation sanguine et lymphatique. Utilisez-la en diffusion ou ajoutez-la à un bain détoxifiant pour profiter de ses effets purifiants.', 
    UNIX_TIMESTAMP(), 
    20, 
    9),
(70, 'Comment Créer une Brume d’Oreiller Relaxante avec de l’Huile de Lavande et de Camomille', 
    'Préparez une brume d’oreiller relaxante en combinant de l’eau avec des huiles essentielles de lavande et de camomille. Vaporisez sur votre oreiller avant de dormir pour améliorer la qualité du sommeil.', 
    UNIX_TIMESTAMP(), 
    22, 
    10),
(71, 'Les Bienfaits de l’Huile Essentielle de Bois de Santal pour la Méditation', 
    'L’huile essentielle de bois de santal est idéale pour favoriser la concentration et la méditation. Utilisez-la en diffusion ou appliquez-la sur les poignets avant de méditer pour une expérience plus profonde.', 
    UNIX_TIMESTAMP(), 
    25, 
    1),
(72, 'Préparer un Masque Réparateur pour Cheveux Abîmés', 
    'Un masque réparateur pour cheveux abîmés peut être fabriqué en combinant de l’huile d’argan, du miel et quelques gouttes d’huile essentielle de ylang-ylang. Ce masque nourrit les cheveux en profondeur et leur redonne brillance et douceur.', 
    UNIX_TIMESTAMP(), 
    30, 
    2),
(73, 'Comment Utiliser l’Huile de Lavande pour Apaiser les Irritations Cutanées', 
    'L’huile essentielle de lavande est excellente pour apaiser les irritations cutanées. Diluez-la avec une huile de support et appliquez sur la zone affectée pour soulager les démangeaisons et les rougeurs.', 
    UNIX_TIMESTAMP(), 
    12, 
    3),
(74, 'Les Propriétés Raffermissantes de l’Huile Essentielle de Myrrhe', 
    'L’huile essentielle de myrrhe est connue pour ses propriétés raffermissantes et anti-âge. En l’ajoutant à votre crème de jour ou de nuit, elle aide à améliorer l’élasticité de la peau et à réduire les signes du vieillissement.', 
    UNIX_TIMESTAMP(), 
    17, 
    4),
(75, 'Préparer une Lotion Anti-Cellulite avec de l’Huile de Pamplemousse', 
    'Une lotion anti-cellulite peut être fabriquée en combinant de l’huile de pamplemousse avec de l’huile de coco et quelques gouttes d’huile essentielle de géranium. Cette lotion aide à tonifier la peau et à améliorer l’apparence de la cellulite.', 
    UNIX_TIMESTAMP(), 
    20, 
    5),
(76, 'Les Avantages de l’Huile Essentielle de Carotte pour les Peaux Sensibles', 
    'L’huile essentielle de carotte est excellente pour les peaux sensibles et réactives. Elle aide à régénérer et à apaiser la peau. Mélangez-la avec une huile de base comme l’huile d’amande douce et appliquez sur le visage pour un effet calmant.', 
    UNIX_TIMESTAMP(), 
    22, 
    6),
(77, 'Créer un Nettoyant Maison pour les Pores Obstrués avec du Charbon Actif', 
    'Préparez un nettoyant efficace pour les pores obstrués en combinant du charbon actif avec de l’eau et quelques gouttes d’huile essentielle de tea tree. Ce nettoyant aide à purifier la peau et à réduire les impuretés.', 
    UNIX_TIMESTAMP(), 
    25, 
    7),
(78, 'Les Propriétés Antiviral de l’Huile Essentielle de Thym pour l’Hiver', 
    'L’huile essentielle de thym possède des propriétés antivirales puissantes. Utilisez-la en diffusion pendant la saison hivernale pour renforcer les défenses naturelles de votre organisme et aider à prévenir les infections.', 
    UNIX_TIMESTAMP(), 
    30, 
    8),
(79, 'Comment Utiliser l’Huile Essentielle d’Eucalyptus pour Soulager la Congestion', 
    'L’huile essentielle d’eucalyptus est idéale pour soulager la congestion et les symptômes du rhume. En diffusion ou en inhalation, elle aide à dégager les voies respiratoires et à améliorer la respiration.', 
    UNIX_TIMESTAMP(), 
    12, 
    9),
(80, 'Préparer une Crème Hydratante pour les Jambes Sèches avec de l’Huile d’Amande Douce', 
    'Une crème hydratante pour les jambes sèches peut être fabriquée en combinant de l’huile d’amande douce, du beurre de karité et quelques gouttes d’huile essentielle de lavande. Cette crème nourrit et adoucit les jambes sèches.', 
    UNIX_TIMESTAMP(), 
    15, 
    10),
(81, 'Les Bienfaits de l’Huile Essentielle de Camomille pour le Stress et l’Anxiété', 
    'L’huile essentielle de camomille est bénéfique pour réduire le stress et l’anxiété. En diffusion ou en application locale sur les poignets, elle aide à créer un environnement calme et apaisant.', 
    UNIX_TIMESTAMP(), 
    17, 
    1),
(82, 'Créer un Baume Nourrissant pour les Lèvres avec de l’Huile de Jojoba', 
    'Un baume à lèvres nourrissant peut être préparé en combinant de l’huile de jojoba, du beurre de cacao et quelques gouttes d’huile essentielle de menthe. Ce baume hydrate les lèvres tout en leur donnant une sensation rafraîchissante.', 
    UNIX_TIMESTAMP(), 
    20, 
    2),
(83, 'Les Propriétés Purifiantes de l’Huile Essentielle de Cèdre pour la Peau Acnéique', 
    'L’huile essentielle de cèdre est efficace pour purifier la peau acnéique. Ajoutez-la à votre routine de soins en la mélangeant avec une huile de support pour aider à réduire les boutons et les imperfections.', 
    UNIX_TIMESTAMP(), 
    22, 
    3),
(84, 'Comment Préparer une Lotion Après-Soleil Apaisante avec de l’Huile de Lavande', 
    'Préparez une lotion après-soleil apaisante en combinant de l’huile de lavande, du gel d’aloe vera et de l’huile de coco. Cette lotion aide à calmer la peau après une exposition au soleil et à prévenir la sécheresse.', 
    UNIX_TIMESTAMP(), 
    25, 
    4),
(85, 'Les Bienfaits de l’Huile Essentielle de Santal pour les Peaux Seches', 
    'L’huile essentielle de santal est idéale pour les peaux sèches en raison de ses propriétés hydratantes et nourrissantes. Mélangez-la avec une huile de base comme l’huile d’argan et appliquez sur le visage pour une peau douce et souple.', 
    UNIX_TIMESTAMP(), 
    30, 
    5),
(86, 'Préparer un Sérum Régénérant pour les Cheveux Abîmés avec de l’Huile d’Argan', 
    'Un sérum régénérant pour cheveux abîmés peut être fabriqué en combinant de l’huile d’argan, de l’huile essentielle de romarin et du miel. Ce sérum restaure la brillance et la douceur des cheveux.', 
    UNIX_TIMESTAMP(), 
    12, 
    6),
(87, 'Les Propriétés Régénérantes de l’Huile Essentielle de Bois de Rose pour la Peau', 
    'L’huile essentielle de bois de rose est excellente pour régénérer la peau et atténuer les cicatrices. Ajoutez-la à vos produits de soins ou utilisez-la en massage pour une peau plus lisse et éclatante.', 
    UNIX_TIMESTAMP(), 
    17, 
    7),
(88, 'Créer un Gommage Corporel Nourrissant avec de l’Huile de Coco et du Café', 
    'Un gommage corporel nourrissant peut être préparé en combinant du café moulu avec de l’huile de coco et quelques gouttes d’huile essentielle de vanille. Ce gommage exfolie et hydrate la peau tout en laissant un parfum agréable.', 
    UNIX_TIMESTAMP(), 
    20, 
    8),
(89, 'Les Avantages de l’Huile Essentielle de Mandarine pour la Peau Fatiguée', 
    'L’huile essentielle de mandarine est idéale pour revitaliser la peau fatiguée. Ajoutez-la à votre crème de nuit ou utilisez-la en diffusion pour un effet énergisant et rafraîchissant.', 
    UNIX_TIMESTAMP(), 
    22, 
    9),
(90, 'Préparer un Nettoyant Visage Exfoliant avec de l’Huile d’Olive et du Sel', 
    'Préparez un nettoyant exfoliant pour le visage en combinant de l’huile d’olive, du sel fin et quelques gouttes d’huile essentielle de rose. Ce nettoyant élimine les cellules mortes et laisse la peau douce et éclatante.', 
    UNIX_TIMESTAMP(), 
    25, 
    10),
(91, 'Les Propriétés Apaisantes de l’Huile Essentielle de Camomille pour les Yeux Fatigués', 
    'L’huile essentielle de camomille est idéale pour apaiser les yeux fatigués. Diluez-la avec une huile de support et appliquez délicatement autour des yeux pour réduire les cernes et les poches.', 
    UNIX_TIMESTAMP(), 
    30, 
    1),
(92, 'Comment Préparer un Baume Réparateur pour les Ongles Abîmés', 
    'Préparez un baume réparateur pour les ongles en combinant de l’huile de ricin, du beurre de karité et quelques gouttes d’huile essentielle de tea tree. Ce baume renforce et nourrit les ongles tout en prévenant les infections.', 
    UNIX_TIMESTAMP(), 
    12, 
    2),
(93, 'Les Bienfaits de l’Huile Essentielle de Basilic pour la Concentration', 
    'L’huile essentielle de basilic est utile pour améliorer la concentration et la clarté mentale. Utilisez-la en diffusion ou ajoutez quelques gouttes à un roll-on pour aider à maintenir la concentration tout au long de la journée.', 
    UNIX_TIMESTAMP(), 
    17, 
    3),
(94, 'Préparer une Lotion Revitalisante pour le Corps avec du Citron et du Gingembre', 
    'Préparez une lotion revitalisante en combinant du citron, du gingembre et de l’huile d’amande douce. Cette lotion stimule la circulation sanguine et revitalise la peau, la laissant douce et parfumée.', 
    UNIX_TIMESTAMP(), 
    20, 
    4);
