INSERT INTO Categorie (id, name) VALUES
(1, 'Huiles essentielles'),
(2, 'Diffusion d’huiles'),
(3, 'Utilisation thérapeutique'),
(4, 'Cosmétique naturelle'),
(5, 'Relaxation et bien-être'),
(6, 'Massages aromatiques'),
(7, 'Recettes maison'),
(8, 'Aromathérapie pour enfants'),
(9, 'Huiles pour le sommeil'),
(10, 'Aromathérapie et santé mentale'),
(11, 'Aromathérapie pour animaux'),
(12, 'Précautions et contre-indications'),
(13, 'Huiles pour la digestion'),
(14, 'Aromathérapie et grossesse'),
(15, 'Huiles pour les douleurs articulaires'),
(16, 'Entretien de la maison avec les huiles'),
(17, 'Huiles essentielles bio'),
(18, 'Aromathérapie et système immunitaire'),
(19, 'Aromathérapie énergétique'),
(20, 'Formations et ateliers d’aromathérapie');
