INSERT INTO Recipe (id, title, ingredients, instructions, description, date_published, auteur_id) VALUES
(1, 'Baume relaxant à la lavande', 
    'Huile essentielle de lavande, Huile de coco, Cire d’abeille', 
    'Faites fondre la cire d’abeille avec l’huile de coco, ajoutez l’huile essentielle de lavande. Mélangez et versez dans un pot.', 
    'Un baume apaisant parfait pour la relaxation et le soulagement des tensions.', 
    UNIX_TIMESTAMP(), 
    2),
(2, 'Spray d’ambiance purifiant', 
    'Huile essentielle d’eucalyptus, Huile essentielle de citron, Eau distillée', 
    'Mélangez les huiles essentielles avec l’eau dans un vaporisateur. Secouez avant chaque utilisation.', 
    'Un spray maison pour purifier l’air et créer une atmosphère fraîche.', 
    UNIX_TIMESTAMP(), 
    5),
(3, 'Huile de massage anti-stress', 
    'Huile essentielle de lavande, Huile essentielle de camomille, Huile d’amande douce', 
    'Mélangez les huiles essentielles avec l’huile d’amande douce dans un flacon. Utilisez pour masser les zones de tension.', 
    'Une huile de massage relaxante pour réduire le stress et favoriser la détente.', 
    UNIX_TIMESTAMP(), 
    8),
(4, 'Baume apaisant pour maux de tête', 
    'Huile essentielle de menthe poivrée, Huile essentielle de lavande, Huile de jojoba', 
    'Mélangez les huiles essentielles avec l’huile de jojoba. Appliquez sur les tempes et le cou.', 
    'Un baume naturel pour soulager les maux de tête.', 
    UNIX_TIMESTAMP(), 
    5),
(5, 'Diffuseur d’huiles pour le sommeil', 
    'Huile essentielle de lavande, Huile essentielle de marjolaine, Diffuseur d’huiles', 
    'Ajoutez quelques gouttes des huiles essentielles dans le diffuseur. Diffusez dans la chambre avant le coucher.', 
    'Une synergie d’huiles essentielles pour favoriser un sommeil réparateur.', 
    UNIX_TIMESTAMP(), 
    2),
(6, 'Sérum visage hydratant à l’aloe vera', 
    'Gel d’aloe vera, Huile essentielle de géranium, Huile d’argan', 
    'Mélangez tous les ingrédients et appliquez sur le visage après nettoyage.', 
    'Un sérum hydratant naturel pour une peau éclatante et en bonne santé.', 
    UNIX_TIMESTAMP(), 
    8),
(7, 'Huile corporelle énergisante', 
    'Huile essentielle d’orange, Huile essentielle de pamplemousse, Huile de pépins de raisin', 
    'Mélangez les huiles essentielles avec l’huile de pépins de raisin. Appliquez sur le corps après la douche.', 
    'Une huile revigorante pour dynamiser et hydrater la peau.', 
    UNIX_TIMESTAMP(), 
    5),
(8, 'Roll-on relaxant pour le voyage', 
    'Huile essentielle de lavande, Huile essentielle de bergamote, Huile de jojoba', 
    'Mélangez les huiles essentielles avec l’huile de jojoba dans un flacon roll-on. Appliquez sur les poignets lors des voyages.', 
    'Un roll-on pratique pour se relaxer durant les trajets en avion ou en voiture.', 
    UNIX_TIMESTAMP(), 
    2),
(9, 'Inhalateur pour la congestion nasale', 
    'Huile essentielle d’eucalyptus, Huile essentielle de menthe poivrée, Inhalateur', 
    'Ajoutez quelques gouttes des huiles essentielles dans un inhalateur. Utilisez en cas de congestion nasale.', 
    'Un inhalateur efficace pour déboucher les voies respiratoires en cas de rhume.', 
    UNIX_TIMESTAMP(), 
    8),
(10, 'Lotion après-soleil apaisante', 
    'Gel d’aloe vera, Huile essentielle de lavande, Huile essentielle de tea tree', 
    'Mélangez tous les ingrédients et appliquez sur la peau après une exposition au soleil.', 
    'Une lotion apaisante pour hydrater et calmer la peau après un coup de soleil.', 
    UNIX_TIMESTAMP(), 
    5),
(11, 'Gel douche rafraîchissant à la menthe', 
    'Huile essentielle de menthe poivrée, Gel de base neutre, Huile essentielle de tea tree', 
    'Mélangez les huiles essentielles avec le gel neutre. Utilisez sous la douche pour un effet rafraîchissant.', 
    'Un gel douche énergisant idéal pour commencer la journée.', 
    UNIX_TIMESTAMP(), 
    2),
(12, 'Masque capillaire nourrissant à l’avocat', 
    'Huile essentielle de romarin, Purée d’avocat, Huile d’olive', 
    'Mélangez tous les ingrédients et appliquez sur les cheveux. Laissez poser 30 minutes avant de rincer.', 
    'Un masque naturel pour nourrir les cheveux en profondeur.', 
    UNIX_TIMESTAMP(), 
    5),
(13, 'Déodorant maison à la lavande', 
    'Huile essentielle de lavande, Bicarbonate de soude, Huile de coco', 
    'Mélangez les ingrédients et placez dans un petit pot. Appliquez sur les aisselles.', 
    'Un déodorant naturel et efficace contre les mauvaises odeurs.', 
    UNIX_TIMESTAMP(), 
    8),
(14, 'Sérum capillaire anti-chute', 
    'Huile essentielle de cèdre, Huile essentielle de romarin, Huile de ricin', 
    'Mélangez les huiles dans un flacon. Appliquez sur le cuir chevelu et massez.', 
    'Un sérum fortifiant pour prévenir la chute des cheveux.', 
    UNIX_TIMESTAMP(), 
    5),
(15, 'Baume à lèvres réparateur au karité', 
    'Beurre de karité, Huile essentielle de menthe, Cire d’abeille', 
    'Faites fondre le beurre de karité et la cire, ajoutez l’huile essentielle. Versez dans un petit pot.', 
    'Un baume hydratant pour protéger et réparer les lèvres sèches.', 
    UNIX_TIMESTAMP(), 
    2),
(16, 'Lotion tonique à l’eau de rose', 
    'Eau de rose, Huile essentielle de géranium, Glycérine végétale', 
    'Mélangez tous les ingrédients dans un flacon pulvérisateur. Appliquez sur le visage après le nettoyage.', 
    'Une lotion tonifiante pour rafraîchir et hydrater la peau.', 
    UNIX_TIMESTAMP(), 
    8),
(17, 'Baume chauffant pour douleurs musculaires', 
    'Huile essentielle de gingembre, Huile essentielle de poivre noir, Cire d’abeille', 
    'Faites fondre la cire d’abeille, ajoutez les huiles essentielles. Appliquez sur les muscles douloureux.', 
    'Un baume chauffant pour soulager les douleurs musculaires.', 
    UNIX_TIMESTAMP(), 
    2),
(18, 'Inhalateur contre le rhume', 
    'Huile essentielle d’eucalyptus, Huile essentielle de menthe poivrée, Inhalateur', 
    'Ajoutez quelques gouttes des huiles essentielles dans un inhalateur. Utilisez en cas de rhume.', 
    'Un remède simple et naturel pour soulager la congestion nasale.', 
    UNIX_TIMESTAMP(), 
    8),
(19, 'Gommage corporel au café', 
    'Marc de café, Huile essentielle d’orange, Huile de coco', 
    'Mélangez tous les ingrédients et appliquez sur la peau humide en massant.', 
    'Un gommage revitalisant pour exfolier et adoucir la peau.', 
    UNIX_TIMESTAMP(), 
    5),
(20, 'Huile de bain relaxante à la lavande', 
    'Huile essentielle de lavande, Huile d’amande douce, Lait en poudre', 
    'Mélangez les ingrédients et versez dans un bain chaud. Profitez d’un moment de détente.', 
    'Une huile de bain relaxante pour apaiser le corps et l’esprit.', 
    UNIX_TIMESTAMP(), 
    5),
(21, 'Sels de bain détox au citron', 
    'Sel d’Epsom, Huile essentielle de citron, Bicarbonate de soude', 
    'Mélangez les ingrédients dans un bocal et ajoutez à l’eau du bain.', 
    'Des sels de bain purifiants pour une expérience de spa à la maison.', 
    UNIX_TIMESTAMP(), 
    2),
(22, 'Baume anti-piqûres d’insectes', 
    'Huile essentielle de lavande, Huile essentielle de tea tree, Huile de calendula', 
    'Mélangez les huiles dans un petit pot. Appliquez sur les piqûres pour apaiser la peau.', 
    'Un baume apaisant pour calmer les irritations causées par les piqûres d’insectes.', 
    UNIX_TIMESTAMP(), 
    8),
(23, 'Masque purifiant à l’argile verte', 
    'Argile verte, Eau de rose, Huile essentielle de tea tree', 
    'Mélangez tous les ingrédients pour former une pâte. Appliquez sur le visage et laissez poser 15 minutes.', 
    'Un masque purifiant pour les peaux grasses et à imperfections.', 
    UNIX_TIMESTAMP(), 
    5),
(24, 'Brume d’oreiller pour un sommeil paisible', 
    'Huile essentielle de lavande, Eau distillée, Alcool à friction', 
    'Mélangez les ingrédients dans un flacon pulvérisateur. Vaporisez sur l’oreiller avant de dormir.', 
    'Une brume relaxante pour favoriser un sommeil paisible.', 
    UNIX_TIMESTAMP(), 
    2),
(25, 'Huile corporelle raffermissante', 
    'Huile essentielle de pamplemousse, Huile essentielle de cèdre, Huile d’amande douce', 
    'Mélangez les huiles essentielles avec l’huile d’amande douce. Appliquez sur le corps en massant.', 
    'Une huile raffermissante pour tonifier la peau.', 
    UNIX_TIMESTAMP(), 
    8),
(26, 'Spray purifiant pour la maison', 
    'Huile essentielle de citron, Huile essentielle de tea tree, Eau distillée', 
    'Mélangez les ingrédients dans un flacon pulvérisateur. Utilisez pour désinfecter les surfaces.', 
    'Un spray maison pour purifier l’air et désinfecter les surfaces.', 
    UNIX_TIMESTAMP(), 
    2),
(27, 'Huile essentielle de massage anti-cellulite', 
    'Huile essentielle de pamplemousse, Huile essentielle de genévrier, Huile d’amande douce', 
    'Mélangez les ingrédients et appliquez sur les zones concernées en massant.', 
    'Une huile de massage stimulante pour réduire l’apparence de la cellulite.', 
    UNIX_TIMESTAMP(), 
    5),
(28, 'Crème hydratante pour mains sèches', 
    'Huile essentielle de lavande, Beurre de karité, Huile de coco', 
    'Faites fondre le beurre de karité et l’huile de coco, ajoutez l’huile essentielle de lavande. Appliquez sur les mains.', 
    'Une crème riche et nourrissante pour hydrater les mains sèches.', 
    UNIX_TIMESTAMP(), 
    8),
(29, 'Sérum pour les cils et sourcils', 
    'Huile essentielle de romarin, Huile de ricin, Huile de vitamine E', 
    'Mélangez les ingrédients et appliquez sur les cils et sourcils avant de dormir.', 
    'Un sérum fortifiant pour épaissir les cils et les sourcils.', 
    UNIX_TIMESTAMP(), 
    5),
(30, 'Spray anti-moustique naturel', 
    'Huile essentielle de citronnelle, Huile essentielle de géranium, Eau distillée', 
    'Mélangez les huiles essentielles avec l’eau dans un flacon pulvérisateur. Vaporisez sur la peau.', 
    'Un spray naturel pour repousser les moustiques.', 
    UNIX_TIMESTAMP(), 
    2),
(31, 'Masque cheveux brillants à l’huile de coco', 
    'Huile de coco, Huile essentielle de ylang-ylang, Miel', 
    'Mélangez tous les ingrédients et appliquez sur les cheveux. Laissez poser 30 minutes avant de rincer.', 
    'Un masque nourrissant pour rendre les cheveux brillants et doux.', 
    UNIX_TIMESTAMP(), 
    8);

