INSERT INTO Tag (id, name) VALUES
(1, 'Lavande'),
(2, 'Eucalyptus'),
(3, 'Relaxation'),
(4, 'Anti-stress'),
(5, 'Sommeil'),
(6, 'Huiles végétales'),
(7, 'Respiration'),
(8, 'Anti-inflammatoire'),
(9, 'Diffuseurs d’huiles'),
(10, 'Maux de tête'),
(11, 'Anti-bactérien'),
(12, 'Cicatrisation'),
(13, 'Peau sensible'),
(14, 'Huiles bio'),
(15, 'Concentration'),
(16, 'Immunité'),
(17, 'Recettes DIY'),
(18, 'Santé naturelle'),
(19, 'Tisanes aux huiles'),
(20, 'Huiles pour enfants');
